//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication12.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Question
    {
        public int q_id { get; set; }
        [Required(ErrorMessage = "This Field is Required.")]
        [Display(Name = "Question Statement")]
        [StringLength(300, MinimumLength = 3, ErrorMessage = "Max 300 characters, Minimum 3.")]
        public string statement { get; set; }
        [Required(ErrorMessage = "This Field is Required.")]
        [Display(Name = "Option 1")]
        [StringLength(300, MinimumLength = 3, ErrorMessage = "Max 300 characters, Minimum 3.")]
        public string op1 { get; set; }
        [Required(ErrorMessage = "This Field is Required.")]
        [Display(Name = "Option 2")]
        [StringLength(300, MinimumLength = 3, ErrorMessage = "Max 300 characters, Minimum 3.")]
        public string op2 { get; set; }
        [Required(ErrorMessage = "This Field is Required.")]
        [Display(Name = "Option 3")]
        [StringLength(300, MinimumLength = 3, ErrorMessage = "Max 300 characters, Minimum 3.")]
        public string op3 { get; set; }
        [Required(ErrorMessage = "This Field is Required.")]
        [Display(Name = "Option 4")]
        [StringLength(300, MinimumLength = 3, ErrorMessage = "Max 300 characters, Minimum 3.")]
        public string op4 { get; set; }
        [Required(ErrorMessage = "This Field is Required.")]
        [Display(Name = "Correct option number")]
        public int answer { get; set; }
        public int test_id { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
