//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication12.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Student
    {
        public Student()
        {
            this.Takes = new HashSet<Take>();
        }
    
        public int s_id { get; set; }
        [Required(ErrorMessage = "This Field is Required.")]
        [Display(Name = "Roll Number")]
        public int rollno { get; set; }
        [Required(ErrorMessage = "This Field is Required.")]
        [Display(Name = "Password")]
        [StringLength(50, MinimumLength = 8, ErrorMessage = "Max 50 characters, Minimum 8.")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        public int t_id { get; set; }
    
        public virtual ICollection<Take> Takes { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
